# Generated by Django 2.2.5 on 2021-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('count', models.IntegerField(primary_key=True, serialize=False)),
                ('totalAlphabetical', models.IntegerField()),
                ('totalrealNumber', models.IntegerField()),
                ('totalInteger', models.IntegerField()),
                ('totalAlphanumeric', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
