# Generated by Django 2.2.5 on 2021-05-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
