# Generated by Django 2.2.5 on 2021-05-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210514_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='totalAlphabetical',
            new_name='total_alphabetical',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='totalAlphanumeric',
            new_name='total_alphanumeric',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='totalInteger',
            new_name='total_integer',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='totalrealNumber',
            new_name='total_real_number',
        ),
    ]
