# Generated by Django 2.2.5 on 2021-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210514_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='total_alphabetical',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_alphanumeric',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_integer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_real_number',
            field=models.IntegerField(null=True),
        ),
    ]
