# Generated by Django 2.2.5 on 2021-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20210515_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
